name: Nightly Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install LLVM
      run: |
        sudo apt-get install -y llvm-11-dev liblld-11-dev

    - uses: actions/checkout@v2
    - name: Setup Dependencies
      run: |
        pushd scripts
        chmod +x ./setup-deps.sh
        ./setup-deps.sh
        popd

    - name: Build
      run: |
        cargo build --verbose --release
        strip ./target/release/tinkerlang

    - name: Upload Binary
      uses: actions/upload-artifact@v2.2.2
      with:
        name: tinkerlang-linux
        path: ./target/release/tinkerlang

    - name: Setup Docker Context
      run: |
        echo '**' > .dockerignore
        echo '!/target/release/tinkerlang' >> .dockerignore
        
        echo 'FROM ubuntu:focal' > Dockerfile
        echo 'COPY ./target/release/tinkerlang .' >> Dockerfile
        echo 'ENTRYPOINT ["./tinkerlang"]' >> Dockerfile

    - name: Publish to Github Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: sirjosh3917/tinkerlang/latest
        tag_with_ref: true
