name: Rust

on:
  push:
    branches: [ main, github-actions ]
  pull_request:
    branches: [ main, github-actions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install LLVM
      run: |
        sudo apt-get install -y llvm-dev liblld-11-dev

    - uses: actions/checkout@v2
    
    - name: Setup Dependencies
      run: |
        pushd scripts
        chmod +x ./setup-deps.sh
        ./setup-deps.sh
        popd

    - name: Build
      run: cargo build --verbose --release
